#!/usr/bin/env php
<?php

/**
 * This file is part of the eghojansu/stick library.
 *
 * (c) Eko Kurniawan <ekokurniawanbs@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

if (version_compare('7.1.0', PHP_VERSION, '>')) {
    fwrite(
        STDERR,
        sprintf(
            'This version of Stick is supported on PHP 7.1 and PHP 7.2.'.PHP_EOL.
            'You are using PHP %s (%s).'.PHP_EOL,
            PHP_VERSION,
            PHP_BINARY
        )
    );

    die(1);
}

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('STICK_COMPOSER_INSTALL', $file);

        break;
    }
}

unset($file);

if (!defined('STICK_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:'.PHP_EOL.PHP_EOL.
        '    composer install'.PHP_EOL.PHP_EOL.
        'You can learn all about Composer on https://getcomposer.org/.'.PHP_EOL
    );

    die(1);
}

require STICK_COMPOSER_INSTALL;

Fal\Stick\Fw::createFromGlobals()
    ->registerShutdownHandler()
    ->emulateCliRequest()
    ->execute(array('Fal\\Stick\\Command', 'register'))
    ->run()
;
