DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    password VARCHAR(100) NULL DEFAULT NULL,
    active INT(11) NOT NULL DEFAULT 1
) ENGINE=MyISAM;