<?php

return array(
    'validation' => array(
        'default' => 'This value is not valid.',
        'required' => 'This value should not be blank.',
        'type' => 'This value should be of type {0}.',
        'min' => 'This value should be {0} or more.',
        'max' => 'This value should be {0} or less.',
        'lt' => 'This value should be less than {0}.',
        'gt' => 'This value should be greater than {0}.',
        'lte' => 'This value should be less than or equal to {0}.',
        'gte' => 'This value should be greater than or equal to {0}.',
        'equalfield' => 'This value should be equal to value of {0}.',
        'notequalfield' => 'This value should not be equal to value of {0}.',
        'equal' => 'This value should be equal to {0}.',
        'notequal' => 'This value should not be equal to {0}.',
        'identical' => 'This value should be identical to {1} {0}.',
        'notidentical' => 'This value should not be identical to {1} {0}.',
        'len' => 'This value is not valid. It should have exactly {0} characters.',
        'lenmin' => 'This value is too short. It should have {0} characters or more.',
        'lenmax' => 'This value is too long. It should have {0} characters or less.',
        'count' => 'This collection should contain exactly {0} elements.',
        'countmin' => 'This collection should contain {0} elements or more.',
        'countmax' => 'This collection should contain {0} elements or less.',
        'choice' => 'The value you selected is not a valid choice.',
        'choices' => 'One or more of the given values is invalid.',
        'date' => 'This value is not a valid date.',
        'datetime' => 'This value is not a valid datetime.',
        'email' => 'This value is not a valid email address.',
        'url' => 'This value is not a valid url.',
        'ipv4' => 'This value is not a valid ipv4 address.',
        'ipv6' => 'This value is not a valid ipv6 address.',
        'isprivate' => 'This value is not a private ip address.',
        'isreserved' => 'This value is not a reserved ip address.',
        'ispublic' => 'This value is not a public ip address.',
        'unique' => 'This value is already used.',
        'password' => 'This value should be equal to your user password.',
    ),
);
